<a href="https://colab.research.google.com/github/sushant21csu463/RLLAB/blob/main/Q_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Define the environment matrix
env_matrix = np.array([
    [-1, -1, -1, -1, 0, -1],
    [-1, -1, -1, 0, -1, 100],
    [-1, -1, -1, 0, -1, -1],
    [-1, 0, 0, -1, 0, -1],
    [0, -1, -1, 0, -1, 100],
    [-1, 0, -1, -1, 0, 100]
])

# Initialize the Q-table with zeros
num_states, num_actions = env_matrix.shape
Q = np.zeros((num_states, num_actions))

# Set hyperparameters
gamma = 0.8

# Define the sequence of states
sequence = [1, 3, 5]

# Q-learning algorithm
for state in sequence:
    # Find the non-negative Q-values for the possible actions in the current state
    possible_actions = np.where(env_matrix[state] >= 0)[0]

    # Update the Q-values for each possible action
    for action in possible_actions:
        Q[state, action] = env_matrix[state, action] + gamma * np.max(Q[action])

    # Print the updated Q-table
    print("Q-table after state", state)
    print(Q)

print("Final Q-table:")
print(Q)

Q-table after state 1
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]
Q-table after state 3
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.  80.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]
Q-table after state 5
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.  80.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.  80.   0.   0.   0. 164.]]
Final Q-table:
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.  80.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.  80.   0.   0.   0. 164.]]
